server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sports-store
    username: root
    password: admin
  application:
    name: ecommerce-store-spring
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
